### ISSUE TITLE
Yaml with emoji cause error "the stream contains non-printable characters" 

### ISSUE THREAD

**Issue by jseguillon** [redhat-developer/yaml-language-server#128] opened 2019-02-26 17:04 UTC
While using vscode + YAML Language support extensions (version 0.3.0), I found that using emojis cause errors :

- VSCode Version:
```bash 
code --version 
1.31.1
1b8e8302e405050205e69b59abb3559592bb9e60
x64
```
- OS Version:
```bash 
cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
...
UBUNTU_CODENAME=bionic
```
Steps to Reproduce:

1. Create a test.yml file with this content as this there is no parsing error (extract from a gitlab-ci.yml file) : 
```yaml
stages:
  - build

build:
  stage: build
  before_script:
    - echo "hi"
  script:
    - echo "hi"
```
2.  Create a test.yml with the same content but using also some emojis : 
```yaml
stages:
  - build

build:
  stage: build
  before_script:
    - echo "📢 - hi - 👷"
  script:
    - echo "📢 - hi - 👷"
```

This leads to the following errors : 
```json
{
	"resource": "/test.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "the stream contains non-printable characters",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}
{
	"resource": "/test.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "incomplete explicit mapping pair; a key node is missed",
	"startLineNumber": 1,
	"startColumn": 7,
	"endLineNumber": 2,
	"endColumn": 5
}
{
	"resource": "/test.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "end of the stream or a document separator is expected",
	"startLineNumber": 2,
	"startColumn": 3,
	"endLineNumber": 4,
	"endColumn": 2
}
{
	"resource": "/test.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "end of the stream or a document separator is expected",
	"startLineNumber": 4,
	"startColumn": 6,
	"endLineNumber": 5,
	"endColumn": 4
}
```

**Comment by ssbarnea** [comment] 2020-06-02 07:56
Considering that the upstream library seems not well maintained, do we have any options to switch to other libraries?

**Comment by gorkem** [comment] 2020-11-21 05:55
Is this issue still valid? I could not reproduce the error locally. I have also added a [test](https://github.com/redhat-developer/yaml-ast-parser/pull/12) to cover emojis on the parser which seems to be happy.

**Comment by manics** [comment] 2020-11-21 12:40
Testing the today it looks like the YAML language server is fine on it's own. If I enable the [Microsoft Ansible plugin](https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible) I see the above errors (`the stream contains non-printable characters` ...), might be worth bearing in mind for anyone else running into this problem.

**Comment by gorkem** [comment] 2020-11-21 13:55
That explains. vscode-ansible has an old copy of the extension embedded. Unfortunately that project seems to be unmaintained and we could not get them to use vscode-yaml, instead of embedding the language server.

**Comment by ssbarnea** [comment] 2020-11-22 12:21
I have being watching the discussions on both sides and to be honest I do think that there is something `vscode-yaml` must do first: be able to identify and lint ansible code with default configuration (no user intervention).

Without this, I cannot blame vscode-ansible project owners from not having trust in vscode-yaml, even if I know it works. It is like shipping a car that needs to be taken to the service before driving ;)

**Comment by gorkem** [comment] 2020-11-23 17:23
Closing.. Tests are merged. vscode-ansible is a separate issue that we have been following up for a while and failing to get a respond.

**Closed by gorkem** 2020-11-23 17:23 UTC
Labels: bug, parser issue, upstream
