### ISSUE TITLE
Support relative $schema modeline

### ISSUE THREAD

**Issue by remcohaszing** [redhat-developer/yaml-language-server#502] opened 2021-07-07 09:57 UTC
### Is your enhancement related to a problem? Please describe.
Helm charts contain a `values.yaml` file for default values. This may be accompanied by a `values.schema.json` file in the same directory.

A reference can be found [here](https://helm.sh/docs/topics/charts/#the-chart-file-structure)

A modeline comment can be added to YAML files to get JSON schema validation, however, it doesn’t resolve relative files.

```yaml
# yaml-language-server: $schema=values.schema.json
# yaml-language-server: $schema=./values.schema.json
# yaml-language-server: $schema=file://./values.schema.json
```

### Describe the solution you would like
I would like the language server to be able to resolve a JSON schema relative to the file containing a modeline.

### Describe alternatives you have considered
It’s possible to use some hardcoded paths in VSCode settings, but this isn’t ideal.

**Comment by evidolob** [comment] 2021-07-07 11:23
Duplicate of https://github.com/redhat-developer/yaml-language-server/issues/371

**Closed** 2021-07-07 11:27 UTC
