### ISSUE TITLE
Local YAML schema applied to itself

### ISSUE THREAD

**Issue by odiak** [redhat-developer/yaml-language-server#871] opened 2023-04-21 05:39 UTC
## Describe the bug

Related to https://github.com/redhat-developer/vscode-yaml/issues/894.

I'm using YAML VSCode extension.
I wrote a custom YAML schema in a project and associate its schema to some files in the project using VSCode setting like below.

```
// .vscode/settings.json
// ...
  "yaml.schemas": {
    "./schemas/custom.yml": [ "./a/config.yml", "./b/config.yml" ]
  }
// ...
```

Though `./schemas/custom.yml` is applied to `./{a,b}/config.yml`, but it is also applied to `./schemas/custom.yml` itself.

## Expected Behavior

The schema `./schemas/custom.yml` is NOT applied to `schemas/custom.yml` itself.

## Current Behavior

The schema `./schemas/custom.yml` is NOT applied to `schemas/custom.yml` itself.

## Steps to Reproduce

1. Open a project in VSCode (YAML extension was installed)
2. Write custom YAML schema `schemas/custom.yml`
3. Associate the schema to some files by `"yaml.schemas"` setting in `.vscode/settings.json`

## Environment
- [ ] Windows
- [x] Mac
- [ ] Linux
- [ ] other (please specify)

**Comment by odiak** [comment] 2023-04-21 05:41
I roughly read source code, and I thought code below might cause this issue.

https://github.com/redhat-developer/yaml-language-server/blob/cf3f79202524ba979f1f4011636b85d08d81bdcb/src/languageservice/services/yamlSchemaService.ts#L408-L417

**Comment by odiak** [comment] 2023-04-21 05:44
@JPinkney As original author of that code, how do you think of this problem?

**Comment by DetachHead** [comment] 2023-06-15 08:55
duplicate of #477

**Closed** 2023-06-22 16:37 UTC
Labels: bug
